### ISSUE TITLE
Create a calendar activity

### ISSUE THREAD

**Issue by AttiaYoussef** [MrZaiko/Polysmee#14]

**Comment by AttiaYoussef** [comment]
@MRandl @MrZaiko @Morpheo1 @tombenamato @Fermeli I was thinking a bit about the format the calendar should take (at least until next week) , and was thinking that maybe for now we should settle on showing the user his daily meetings? From what I saw the APIs to create calendars don't mix well with how we want the calendar to work (tapping a specific event to see its details like the time, course, etc), and I don't know if I can manage a full monthly/yearly calendar at the end of next week. What do you guys think?

**Comment by MRandl** [comment]
> @MRandl @MrZaiko @Morpheo1 @tombenamato @Fermeli I was thinking a bit about the format the calendar should take (at least until next week) , and was thinking that maybe for now we should settle on showing the user his daily meetings? From what I saw the APIs to create calendars don't mix well with how we want the calendar to work (tapping a specific event to see its details like the time, course, etc), and I don't know if I can manage a full monthly/yearly calendar at the end of next week. What do you guys think?

Agree. Showing a list will be much easier to handle for the first working prototype. We can always implement another way to display those when we feel like it.

**Comment by MrZaiko** [comment]
I also agree.
