### ISSUE TITLE
Git local config

### ISSUE THREAD

**Issue by samuelchassot** [MrZaiko/Polysmee#60]
Hi @tombenamato!

I went through your PRs and it seems that you did something wrong with your local git config because your commits are not linked to your account. You should have a look :)

Feel free to ask if you don't know how to solve :)

Best

**Comment by tombenamato** [comment]
Hi @samuelchassot.
I indeed don't know how to solve it, do you have any link that I can follow to be sure my next commits are linked to my account

**Comment by samuelchassot** [comment]
Hi,
Yep, the most probable issue is that you don't have matching email/username in your local git settings and on Github.
https://git-scm.com/book/en/v2/Getting-Started-First-Time-Git-Setup 
If you follow the link, you'll find a section "Your identity". The username and email must match the one used on Github.

Don't hesitate to tell me if that doesn't help :)

**Comment by tombenamato** [comment]
So indeed there my local email and username was not matching with the one on my github account I changed it. How can I check that the problem is indeed resolve ?

**Comment by samuelchassot** [comment]
You can commit to a branch some changes then open a PR, the little profile picture next to the commits should match your GitHub one. Moreover, if you hover it, it should link to your profile.

**Comment by tombenamato** [comment]
I think my problem is resolved
